### PR TITLE
added Samtec LSHM connectors

### PR DESCRIPTION
**Pull request by ashtonchase**
Connector PDF:
http://suddendocs.samtec.com/catalog_english/lshm_dv.pdf

Footprint PDF:
http://suddendocs.samtec.com/prints/lshm-1xx-xx.x-x-dv-a-x-x-tr-footprint.pdf

### CODE REVIEW

**Comment by ashtonchase** [comment]
footprint link:
http://suddendocs.samtec.com/prints/lshm-1xx-xx.x-x-dv-a-x-x-tr-footprint.pdf

**Comment by CarlPoirier** [comment]
Hi @ashtonchase,

Please check your pull request using the check_kicad_mod.py script available here: https://github.com/KiCad/kicad-library-utils/tree/master/pcb

You will see there are some violations. If you need further help in fixing your footprints, just let me know!

**Comment by pointhi** [comment]
@CarlPoirier I would suggest to create a new repo for samtec connectors. In my oppinion vendor specific connectors should move out from Connect.pretty

**Comment by CarlPoirier** [comment]
Hi @ashtonchase,

Please apply the same comments I wrote in https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/5. Notice that the mounting holes also need to be inside the courtyard. Also, for a connector, its clearance is 0.5 as per rule 6.7.

Lastly, I created a new repository here so please open a new PR for it: https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/5

Regards,

Carl

**Comment by pointhi** [comment]
@CarlPoirier you have forgotten to add the .pretty suffix, and to transfer the repo to the library team

**Comment by CarlPoirier** [comment]
Indeed! I added the suffix, but the write rights should have been working already!

**Pull request closed without merging**
