### PR TITLE
Mini-DIN 6 Pins Connector

### PR DESCRIPTION
**Pull request by 4x1md**
A footprint for the Mini-DIN 6 pins connector with metal shell. I attached the photo and the datasheet.

mini-din-5-aliexpress-01

mini-din-5-aliexpress-02

### CODE REVIEW

**Comment by jkriege2** [comment]
Please add a link to a 3D model (even if none exists). Could you also try and find a datasheet that matches this footprint and add its link to the description?
Otherwise this looks fine to me.

Best,
JAN

**Comment by jkriege2** [comment]
This PR should provide an appropriate symbol: https://github.com/KiCad/kicad-library/pull/1189

**Comment by jkriege2** [comment]
@4x5dm Did you see my comments above?

Best,
JAN

**Comment by 4x5dm** [comment]
Yes. I'll correct the PR later.

**Comment by jkriege2** [comment]
Great! I'll merge it when done :-)

**Comment by 4x5dm** [comment]
BTW, in my [Custom KiCad Libraries repository](https://github.com/4x5dm/kicad_libraries) I have symbols for this connector.

**Comment by 4x5dm** [comment]
I couldn't find an exact datasheet. They are all similar. The only exact one is in AliExpress lots where I actually bought these connectors for me: https://www.aliexpress.com/item//32763907815.html

As to link to a 3D model, what exactly am I supposed to do?

**Comment by jkriege2** [comment]
Hi! Sorry for the delay in my answer ...

The AliExpress parts seem to be from `RTLECS` and named `MDC-6-03 -10` (according to you link). Therefore we should rename this maybe to `Mini-DIN-6_Female_RTLECS_MDC-6-03`

For the 3D model, please simply add a 3D model (even if it does not exist yet): `${KISYS3DMOD}/Connectors.3dshapes\Mini-DIN-6_Female_RTLECS_MDC-6-03.wrl` (scaling 1,1,1, offset 0,0,0). This way, if somebody provides/has the 3D model it is automatically displayed without a change to the footprint.

Best,
JAN

**Comment by Shackmeister** [comment]
Hi @4x1md are you planning on continueing with this footprint? :)

**Comment by 4x1md** [comment]
Yes. I hope to return to it during the next weeks.

**Comment by SchrodingersGat** [comment]
Thanks for the contribution.

We have now marked this repository as read-only, and new footprint contributions must be made to https://github.com/kicad/kicad-footprints

Sorry for the inconvenience, we are working hard to improve the library quality for the upcoming v5 release. Thanks for your understanding

**Pull request closed without merging**
