### PR TITLE
Add VASCH7x2 IDC-14 board connector footprint.

### PR DESCRIPTION
**Pull request by krtkr**

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi,

Please have a look at the KiCad Library Convention here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention

Your footprint doesn't respect many rules. I know, the existing VASCH connectors do not either because we didn't get to them yet. If you want to fix them as well, please do so.

Thank you!

**Comment by krtkr** [comment]
Sure, I can fix all of them. Actually. I would add the rest of typical VASCH* footprints according to this:
http://lib.chipdip.ru/244/DOC000244920.pdf

I suggest to finish VASCH8x2 first. Once you say it is good, I can update/add rest VASCH* footprints.

Electronics is my hobby. So I will need your help to meet the requirements, at least for the first time. I read the convention, but it is not obvious for me what is wrong and what is correct in the footprint.

Could you make a list of what is wrong?

**Comment by CarlPoirier** [comment]
Hi, please run this: https://github.com/michal777/KiCad_Lib_Check

It should give you good insights!

**Comment by ricardocrudo** [comment]
hello @krtkr this same footprint was already added in pr #33.
Thanks anyway.

**Pull request closed without merging**
