### PR TITLE
added IDC headers, removed redundant "VASCH" connectors

### PR DESCRIPTION
**Pull request by chrisnoisel**
I based my edit on http://lib.chipdip.ru/244/DOC000244920.pdf and the Pin_header footprints.
Not sure about the naming however, feel free to correct me (first footprints I make, really).

Also, since they are dynamically generated by a bash script, I can easily make additional IDC headers (different pin counts) if needed.

IDC_Header_Straight_10pins.kicad_mod

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Very nice. Thank you.

**Comment by matthijskooijman** [comment]
@chrisnoisel, any chance you could also generate the 6pin IDC connector? It's commonly used for AVR ISP programming, which is why I need it. I was going to make one manually, but then found this PR. Perhaps sharing your bash script that generated the footprints here (or in the commit message) is also useful, if a change is needed in the future. 

For consistency, adding the 8-pin version also makes sense (4-pins probably don't exist?).

**Comment by chrisnoisel** [comment]
Sorry @matthijskooijman, I meant to do it earlier. 
I just created a pull request, you can grab it now here : [https://github.com/KiCad/Connectors.pretty/pull/48](https://github.com/KiCad/Connectors.pretty/pull/48)
I lost the script (It was a bit ugly anyway) so I copied and edited the 10-pin version, it was just a matter of subtracting 2.54mm there and there.

**Comment by matthijskooijman** [comment]
@chrisnoisel Thanks!

**Pull request merged**
