### PR TITLE
Mounting hole position fix.

### PR DESCRIPTION
**Pull request by leventelist**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @leventelist can you provide some information on why the change was needed?

**Comment by leventelist** [comment]
Because I realized that the pins are off regarding the specification. See
https://github.com/KiCad/Connectors.pretty/pull/50

Also note that the outline also off centered.


Levente

**Comment by SchrodingersGat** [comment]
Just a couple of issues to fix as outlined [here](https://travis-ci.org/KiCad/Connectors.pretty/builds/276980614?utm_source=github_status&utm_medium=notification)

1. Please fill in the description field for the footprint
1. Please add a second RefDes (text item with value `%R`) on the `F.Fab` layer (just above the name text)
1. Move the RefDes on the `F.Silk` layer so that it is visible after component placement (move it just above the top pins)

**Comment by poeschlr** [comment]
Closing and reopening this for test purposes. (New test scripts.)

**Comment by SchrodingersGat** [comment]
Thanks for the contribution.

We have now marked this repository as read-only, and new footprint contributions must be made to https://github.com/kicad/kicad-footprints

Sorry for the inconvenience, we are working hard to improve the library quality for the upcoming v5 release. Thanks for your understanding

**Pull request closed without merging**
