### PR TITLE
Added various connectors.

### PR DESCRIPTION
**Pull request by crackerizer**

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi,

I still see the footprint anchor in the middle. Also, I see no courtyard. On the wafer_vertical*, there is no need for a double silkscreen outline. As Kerusey mentioned, you will want to add a reference mark for pin 1, as the footprint doesn't indicate it clearly. I suggest you remove the silkscreen line on the pin 1 side.

Thanks,

Carl

**Comment by crackerizer** [comment]
Hello, I fixed all the footprint according to your guide.

**Comment by ricardocrudo** [comment]
There are some KLC details to be fixed yet. You can check some KLC rules using the [check_kicad_mod](https://github.com/KiCad/kicad-library-utils/tree/master/pcb) script.

**Comment by crackerizer** [comment]
Footprints are now passed check script.

**Comment by crackerizer** [comment]
ricardocrudo, I just got corrupted file that can not open in footprint editor after run the script. Let me know If you want the file for debugging.

**Comment by ricardocrudo** [comment]
Hello @crackerizer thanks for the contributions. Could you please re-save the files using Kicad? Also, please turn the GoldTek_* footprints making the pin 1 be in the left / top.

**Comment by crackerizer** [comment]
Hi, I have saved all footprints by Kicad. For Goldtek connector, Pin location is fixed to the current one according to its datasheets (http://www.es.co.th/Schemetic/PDF/SCPXXGS11.PDF, http://www.es.co.th/Schemetic/PDF/SCPXXGR11.PDF).

**Pull request merged**
